ports:
  - port: 8080
    name: Examples Server
  - port: 5008
    name: ELK Server
    onOpen: ignore

tasks:
  - init: |
      yarn
    command: |
      if [[ $NPM_TOKEN ]]; then echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc; fi
      yarn --cwd examples start
