name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Sprotty CI
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      NODE_ENV: production
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'
    - name: Install
      run: npm ci
      env:
        NODE_ENV: development
    - name: Build
      run: npm run build
    - name: Lint
      run: npm run lint
    - name: Test
      run: npm test
